### ISSUE TITLE
Add Logo In The Frontend

### ISSUE THREAD

**Issue by thealphadollar** [icyflame/chillzone-frontend#5]
A logo for chillzone was made (can be found here: https://github.com/metakgp/chillzone/pull/18#issuecomment-507132059)

We should add it as the navbar as well as the icons. More details and conversion tool can be found here: https://realfavicongenerator.net/

**Comment by hugo-s29** [comment]
Hi,
I think I can do this, I've already worked with **react**.
Can I do this one ?
Hugo

**Comment by thealphadollar** [comment]
Sure, please go ahead. I'd be happy to help if you face any issues.

**Comment by hugo-s29** [comment]
Thank you,
Where do you want your logo to be ?

**Comment by thealphadollar** [comment]
The placement is upto you; it should definitely look good.

Secondly, I'd like it to be as the favicon.

**Comment by thealphadollar** [comment]
@hugo-s29 As you can see the logo was added in #6 , please add the corresponding logo as web icon and favicon for the application.

**Comment by hugo-s29** [comment]
Hi,
The logo has been set as the favicon.
However, the logo used in issue #6 is a PNG, and when we scale the logo to be more than 1000px, we will see pixels.
So, in the pull request, I'll add the logo in SVG (a vector image) since this format didn't have this sort of problem.

I'll make the pull request shortly.

Bye,
Hugo

**Comment by hugo-s29** [comment]
Hi,

I made the pull request #7. There are conflicts with some files so I explained everything in the request.

Bye,
Hugo

**Comment by thealphadollar** [comment]
Thanks @hugo-s29 for the contribution. I've handled the PR and put it on deployment.
